-- =====================================================================
-- 0010 — Fail-closed critical auditing (Phase 1.1, commit 2)
--
-- Security-critical state changes may no longer exist without their
-- audit record. Each one moves behind a transactional RPC that applies
-- the state change, writes the critical audit row and emits the domain
-- event in ONE transaction — any failure rolls back all of it.
--
-- The boundary is only real if the direct path is closed, so this
-- migration also DROPS the client write policies on approvals,
-- memberships and agents. After this migration the RPCs below are the
-- only way to mutate those tables from the application.
--
-- Audit guarantees (accurate wording, do not inflate):
--   * append-only for application and database roles
--   * deletion-resistant against ordinary roles
--   * critical audits are atomic with their designated internal state change
--   * NOT tamper-proof (an owner can drop the trigger)
--   * NOT tamper-evident (no hash chaining yet)
--   * NOT globally atomic with third-party systems (Supabase Auth, any
--     future external executor) — those are separate transactional domains
--
-- request_origin enumeration (audit metadata, see write_critical_audit):
--   web       browser session acting through a server action
--   agent     AI agent acting through the tool pipeline
--   cron      scheduled endpoint (bearer authenticated)
--   api       programmatic caller other than the above
--   executor  future approved-action executor (no implementation yet)
--   migration schema migration or maintenance script
-- =====================================================================

-- ---------------------------------------------------------------------
-- Idempotency: a (resource, action, request_id) triple may be applied
-- at most once. The RPCs pre-check inside their transaction; this index
-- is the backstop if a concurrent duplicate slips past the check.
-- ---------------------------------------------------------------------
create unique index if not exists audit_logs_idempotency_idx
  on public.audit_logs (resource_id, action, request_id)
  where request_id is not null and resource_id is not null;

-- Creation is the case the index above cannot cover: the resource id is
-- generated by the operation, so two concurrent calls carrying one
-- request id produce two different resource ids and never collide.
-- These actions are therefore constrained on (action, request_id) alone.
-- Only creations may appear here — an action that legitimately writes
-- many rows under one request id (approval.expired) must never be added.
create unique index if not exists audit_logs_creation_idempotency_idx
  on public.audit_logs (action, request_id)
  where request_id is not null
    and action in ('approval.created', 'membership.created');

-- Advisory lock class reserved for serialising critical creations by
-- request id. (742617, 1) is reserved by 0009 for the PRIME bootstrap
-- and must not be reused here.
--   (742618, hashtext(request_id)) — critical creation idempotency
--
-- The lock makes a concurrent duplicate wait and then observe the
-- committed audit row, so it returns the first result instead of
-- failing. The index above remains the backstop if the lock is bypassed.

-- ---------------------------------------------------------------------
-- Approval transition rules — ONE place. Adding a status means editing
-- this function and nothing else.
--
-- actor_kind: 'prime' | 'system' | 'executor'
-- Returns true when the transition is permitted for that actor kind.
-- ---------------------------------------------------------------------
create or replace function public.approval_transition_allowed(
  p_from public.approval_status,
  p_to public.approval_status,
  p_actor_kind text
)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select case
    -- PRIME resolves pending requests.
    when p_actor_kind = 'prime' and p_from = 'pending'
         and p_to in ('approved', 'rejected', 'modified', 'cancelled') then true
    -- PRIME may cancel a resolved-but-unexecuted request.
    when p_actor_kind = 'prime' and p_from in ('approved', 'modified')
         and p_to = 'cancelled' then true
    -- The system expires anything still actionable.
    when p_actor_kind = 'system' and p_from in ('pending', 'approved', 'modified')
         and p_to = 'expired' then true
    -- Only an executor records the outcome of an approved action.
    when p_actor_kind = 'executor' and p_from in ('approved', 'modified')
         and p_to in ('executed', 'failed') then true
    else false
  end;
$$;

comment on function public.approval_transition_allowed is
  'Single source of approval transition rules. Terminal states: rejected, executed, failed, expired, cancelled.';

-- ---------------------------------------------------------------------
-- Internal helpers. No grants: callable only from inside the definer
-- functions below.
-- ---------------------------------------------------------------------

-- Raises unless the actor holds an active PRIME membership in the org.
create or replace function public.assert_org_prime(p_actor uuid, p_org uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_actor is null or p_org is null then
    raise exception 'not_prime';
  end if;
  if not exists (
    select 1
    from public.memberships m
    join public.roles r on r.id = m.role_id
    where m.profile_id = p_actor
      and m.organization_id = p_org
      and m.status = 'active'
      and r.key = 'prime'
  ) then
    raise exception 'not_prime';
  end if;
end;
$$;

revoke all on function public.assert_org_prime(uuid, uuid) from public;

-- Returns the audit id of an already-applied request, or null.
create or replace function public.prior_request_audit(
  p_resource uuid,
  p_action text,
  p_request_id text
)
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from public.audit_logs a
  where a.resource_id = p_resource
    and a.action = p_action
    and a.request_id = p_request_id
  limit 1;
$$;

revoke all on function public.prior_request_audit(uuid, text, text) from public;

-- Writes a critical audit row. Called only from within a transaction
-- that is also applying the corresponding state change.
create or replace function public.write_critical_audit(
  p_org uuid,
  p_business uuid,
  p_actor_type public.actor_type,
  p_actor uuid,
  p_action text,
  p_resource_type text,
  p_resource uuid,
  p_request_id text,
  p_origin text,
  p_before jsonb,
  p_after jsonb,
  p_metadata jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  if p_request_id is null or pg_catalog.length(p_request_id) = 0 then
    raise exception 'request_id_required';
  end if;
  if p_origin not in ('web', 'agent', 'cron', 'api', 'executor', 'migration') then
    raise exception 'invalid_request_origin';
  end if;

  insert into public.audit_logs
    (organization_id, business_id, actor_type, actor_id, action,
     resource_type, resource_id, request_id, before_data, after_data, metadata)
  values
    (p_org, p_business, p_actor_type, p_actor, p_action,
     p_resource_type, p_resource, p_request_id, p_before, p_after,
     -- request_origin is a trusted system field and wins over any
     -- caller-supplied key of the same name.
     coalesce(p_metadata, '{}'::jsonb) ||
       pg_catalog.jsonb_build_object('request_origin', p_origin))
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.write_critical_audit(
  uuid, uuid, public.actor_type, uuid, text, text, uuid, text, text, jsonb, jsonb, jsonb) from public;

-- ---------------------------------------------------------------------
-- Approval creation — an approval must never exist without its audit row.
-- ---------------------------------------------------------------------
create or replace function public.create_approval_audited(
  p_org uuid,
  p_business uuid,
  p_requested_by_user uuid,
  p_requested_by_agent uuid,
  p_action_type text,
  p_action_payload jsonb,
  p_reason text,
  p_estimated_cost numeric,
  p_currency text,
  p_risk_level public.risk_level,
  p_expires_at timestamptz,
  p_request_id text,
  p_origin text,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_approval uuid;
  v_prior uuid;
begin
  if p_requested_by_user is null and p_requested_by_agent is null then
    raise exception 'requester_required';
  end if;
  if p_request_id is null or pg_catalog.length(p_request_id) = 0 then
    raise exception 'request_id_required';
  end if;

  -- Serialise concurrent callers carrying the same request id, so the
  -- duplicate blocks and then sees the committed row below rather than
  -- racing past the check and creating a second approval.
  perform pg_catalog.pg_advisory_xact_lock(742618, pg_catalog.hashtext(p_request_id));

  -- Idempotent replay: the same request id never creates a second approval.
  select a.resource_id into v_approval
  from public.audit_logs a
  where a.action = 'approval.created' and a.request_id = p_request_id
  limit 1;
  if v_approval is not null then
    return v_approval;
  end if;

  insert into public.approvals
    (organization_id, business_id, requested_by_agent_id, requested_by_user_id,
     action_type, action_payload, reason, estimated_cost, currency, risk_level, expires_at)
  values
    (p_org, p_business, p_requested_by_agent, p_requested_by_user,
     p_action_type, coalesce(p_action_payload, '{}'::jsonb), p_reason,
     p_estimated_cost, p_currency, p_risk_level, p_expires_at)
  returning id into v_approval;

  v_prior := public.write_critical_audit(
    p_org, p_business,
    case when p_requested_by_agent is not null then 'agent' else 'user' end::public.actor_type,
    coalesce(p_requested_by_agent, p_requested_by_user),
    'approval.created', 'approval', v_approval, p_request_id, p_origin,
    null,
    pg_catalog.jsonb_build_object(
      'status', 'pending',
      'action_type', p_action_type,
      'risk_level', p_risk_level,
      'estimated_cost', p_estimated_cost,
      'payload_sha256', pg_catalog.encode(
        pg_catalog.sha256(pg_catalog.convert_to(
          coalesce(p_action_payload, '{}'::jsonb)::text, 'UTF8')), 'hex')),
    coalesce(p_metadata, '{}'::jsonb) ||
      pg_catalog.jsonb_build_object('reason', p_reason));

  insert into public.system_events (organization_id, business_id, event_type, payload, dedupe_key)
  values (p_org, p_business, 'approval.requested',
          pg_catalog.jsonb_build_object('approvalId', v_approval, 'actionType', p_action_type),
          v_approval::text);

  return v_approval;
end;
$$;

-- ---------------------------------------------------------------------
-- PRIME approval transitions.
-- ---------------------------------------------------------------------
create or replace function public.resolve_approval(
  p_actor uuid,
  p_approval uuid,
  p_expected_status public.approval_status,
  p_resolution public.approval_status,
  p_request_id text,
  p_origin text,
  p_modified_payload jsonb default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.approvals%rowtype;
  v_action text;
  v_prior uuid;
begin
  v_action := 'approval.' || p_resolution::text;

  -- Row lock serialises concurrent transitions on this approval.
  select * into v_row from public.approvals where id = p_approval for update;
  if not found then
    raise exception 'approval_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  -- Idempotent replay returns the prior audit row without re-applying.
  v_prior := public.prior_request_audit(p_approval, v_action, p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  if v_row.status is distinct from p_expected_status then
    raise exception 'stale_status';
  end if;
  if not public.approval_transition_allowed(v_row.status, p_resolution, 'prime') then
    raise exception 'invalid_transition';
  end if;

  update public.approvals
  set status = p_resolution,
      approved_by = p_actor,
      approved_at = pg_catalog.now(),
      action_payload = case
        when p_resolution = 'modified' and p_modified_payload is not null
          then p_modified_payload
        else action_payload
      end
  where id = p_approval;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    v_action, 'approval', p_approval, p_request_id, p_origin,
    pg_catalog.jsonb_build_object(
      'status', v_row.status,
      'payload_sha256', pg_catalog.encode(
        pg_catalog.sha256(pg_catalog.convert_to(v_row.action_payload::text, 'UTF8')), 'hex')),
    pg_catalog.jsonb_build_object(
      'status', p_resolution,
      'payload_sha256', pg_catalog.encode(
        pg_catalog.sha256(pg_catalog.convert_to(
          coalesce(p_modified_payload, v_row.action_payload)::text, 'UTF8')), 'hex')),
    pg_catalog.jsonb_build_object(
      'transition', v_row.status::text || '->' || p_resolution::text,
      'expected_status', p_expected_status::text,
      'action_type', v_row.action_type));

  insert into public.system_events (organization_id, business_id, event_type, payload, dedupe_key)
  values (v_row.organization_id, v_row.business_id, v_action,
          pg_catalog.jsonb_build_object('approvalId', p_approval, 'actionType', v_row.action_type),
          p_approval::text || ':' || p_resolution::text);

  return v_prior;
end;
$$;

-- ---------------------------------------------------------------------
-- System expiry. No caller yet; the transition matrix is complete
-- regardless. Idempotent per approval via the request id.
-- ---------------------------------------------------------------------
create or replace function public.expire_approvals(p_request_id text, p_origin text default 'cron')
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.approvals%rowtype;
  v_count integer := 0;
begin
  for v_row in
    select * from public.approvals
    where status in ('pending', 'approved', 'modified')
      and expires_at is not null
      and expires_at <= pg_catalog.now()
    order by id
    for update
  loop
    if public.prior_request_audit(v_row.id, 'approval.expired', p_request_id) is not null then
      continue;
    end if;
    if not public.approval_transition_allowed(v_row.status, 'expired', 'system') then
      continue;
    end if;

    update public.approvals set status = 'expired' where id = v_row.id;

    perform public.write_critical_audit(
      v_row.organization_id, v_row.business_id, 'system', null,
      'approval.expired', 'approval', v_row.id, p_request_id, p_origin,
      pg_catalog.jsonb_build_object('status', v_row.status),
      pg_catalog.jsonb_build_object('status', 'expired'),
      pg_catalog.jsonb_build_object('expires_at', v_row.expires_at));

    insert into public.system_events (organization_id, business_id, event_type, payload, dedupe_key)
    values (v_row.organization_id, v_row.business_id, 'approval.expired',
            pg_catalog.jsonb_build_object('approvalId', v_row.id), v_row.id::text || ':expired');

    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------
-- Execution result recording. service_role only, no caller in Phase 1.1.
-- An executor must not use this until the lease/outbox design lands.
-- ---------------------------------------------------------------------
create or replace function public.record_approval_execution(
  p_approval uuid,
  p_expected_status public.approval_status,
  p_outcome public.approval_status,
  p_result jsonb,
  p_request_id text,
  p_origin text default 'executor'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.approvals%rowtype;
  v_action text;
  v_prior uuid;
begin
  v_action := 'approval.' || p_outcome::text;

  select * into v_row from public.approvals where id = p_approval for update;
  if not found then
    raise exception 'approval_not_found';
  end if;

  v_prior := public.prior_request_audit(p_approval, v_action, p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  if v_row.status is distinct from p_expected_status then
    raise exception 'stale_status';
  end if;
  if not public.approval_transition_allowed(v_row.status, p_outcome, 'executor') then
    raise exception 'invalid_transition';
  end if;

  update public.approvals
  set status = p_outcome,
      executed_at = pg_catalog.now(),
      execution_result = p_result
  where id = p_approval;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'system', null,
    v_action, 'approval', p_approval, p_request_id, p_origin,
    pg_catalog.jsonb_build_object('status', v_row.status),
    pg_catalog.jsonb_build_object('status', p_outcome),
    pg_catalog.jsonb_build_object('transition', v_row.status::text || '->' || p_outcome::text));

  insert into public.system_events (organization_id, business_id, event_type, payload, dedupe_key)
  values (v_row.organization_id, v_row.business_id, v_action,
          pg_catalog.jsonb_build_object('approvalId', p_approval),
          p_approval::text || ':' || p_outcome::text);

  return v_prior;
end;
$$;

-- ---------------------------------------------------------------------
-- Membership mutations. PRIME only, no self-modification, last active
-- PRIME protected so the organization cannot be orphaned.
-- ---------------------------------------------------------------------
create or replace function public.assign_membership(
  p_actor uuid,
  p_org uuid,
  p_profile uuid,
  p_business uuid,
  p_role_key public.role_key,
  p_authority public.authority_level,
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role uuid;
  v_membership uuid;
  v_actor_authority public.authority_level;
begin
  perform public.assert_org_prime(p_actor, p_org);

  if p_actor = p_profile then
    raise exception 'self_modification_denied';
  end if;

  select id into v_role from public.roles where key = p_role_key;
  if v_role is null then
    raise exception 'role_not_found';
  end if;

  -- Authority ceiling: never grant above the actor's own level.
  select max(m.authority_level) into v_actor_authority
  from public.memberships m
  where m.profile_id = p_actor and m.organization_id = p_org and m.status = 'active';
  if v_actor_authority is null or p_authority > v_actor_authority then
    raise exception 'authority_ceiling_exceeded';
  end if;

  if p_request_id is null or pg_catalog.length(p_request_id) = 0 then
    raise exception 'request_id_required';
  end if;

  -- Same generated-resource-id race as create_approval_audited.
  perform pg_catalog.pg_advisory_xact_lock(742618, pg_catalog.hashtext(p_request_id));

  select a.resource_id into v_membership
  from public.audit_logs a
  where a.action = 'membership.created' and a.request_id = p_request_id
  limit 1;
  if v_membership is not null then
    return v_membership;
  end if;

  insert into public.memberships
    (organization_id, business_id, profile_id, role_id, authority_level)
  values (p_org, p_business, p_profile, v_role, p_authority)
  returning id into v_membership;

  perform public.write_critical_audit(
    p_org, p_business, 'user', p_actor,
    'membership.created', 'membership', v_membership, p_request_id, p_origin,
    null,
    pg_catalog.jsonb_build_object(
      'profile_id', p_profile, 'role', p_role_key::text,
      'authority_level', p_authority::text, 'business_id', p_business, 'status', 'active'),
    '{}'::jsonb);

  return v_membership;
end;
$$;

create or replace function public.change_membership_role(
  p_actor uuid,
  p_membership uuid,
  p_expected_role public.role_key,
  p_role_key public.role_key,
  p_authority public.authority_level,
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.memberships%rowtype;
  v_current_role public.role_key;
  v_new_role uuid;
  v_actor_authority public.authority_level;
  v_prior uuid;
begin
  select * into v_row from public.memberships where id = p_membership for update;
  if not found then
    raise exception 'membership_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  if v_row.profile_id = p_actor then
    raise exception 'self_modification_denied';
  end if;

  v_prior := public.prior_request_audit(p_membership, 'membership.role_changed', p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  select r.key into v_current_role from public.roles r where r.id = v_row.role_id;
  if v_current_role is distinct from p_expected_role then
    raise exception 'stale_status';
  end if;

  select max(m.authority_level) into v_actor_authority
  from public.memberships m
  where m.profile_id = p_actor and m.organization_id = v_row.organization_id and m.status = 'active';
  if v_actor_authority is null or p_authority > v_actor_authority then
    raise exception 'authority_ceiling_exceeded';
  end if;

  -- Never remove the last active PRIME.
  if v_current_role = 'prime' and p_role_key <> 'prime' then
    if (select count(*) from public.memberships m
        join public.roles r on r.id = m.role_id
        where m.organization_id = v_row.organization_id
          and m.status = 'active' and r.key = 'prime') <= 1 then
      raise exception 'last_prime_protected';
    end if;
  end if;

  select id into v_new_role from public.roles where key = p_role_key;
  if v_new_role is null then
    raise exception 'role_not_found';
  end if;

  update public.memberships
  set role_id = v_new_role, authority_level = p_authority
  where id = p_membership;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    'membership.role_changed', 'membership', p_membership, p_request_id, p_origin,
    pg_catalog.jsonb_build_object(
      'role', v_current_role::text, 'authority_level', v_row.authority_level::text),
    pg_catalog.jsonb_build_object(
      'role', p_role_key::text, 'authority_level', p_authority::text),
    pg_catalog.jsonb_build_object('profile_id', v_row.profile_id));

  return v_prior;
end;
$$;

create or replace function public.revoke_membership(
  p_actor uuid,
  p_membership uuid,
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.memberships%rowtype;
  v_role public.role_key;
  v_prior uuid;
begin
  select * into v_row from public.memberships where id = p_membership for update;
  if not found then
    raise exception 'membership_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  if v_row.profile_id = p_actor then
    raise exception 'self_modification_denied';
  end if;

  v_prior := public.prior_request_audit(p_membership, 'membership.revoked', p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  if v_row.status <> 'active' then
    raise exception 'stale_status';
  end if;

  select r.key into v_role from public.roles r where r.id = v_row.role_id;
  if v_role = 'prime' then
    if (select count(*) from public.memberships m
        join public.roles r on r.id = m.role_id
        where m.organization_id = v_row.organization_id
          and m.status = 'active' and r.key = 'prime') <= 1 then
      raise exception 'last_prime_protected';
    end if;
  end if;

  update public.memberships set status = 'revoked' where id = p_membership;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    'membership.revoked', 'membership', p_membership, p_request_id, p_origin,
    pg_catalog.jsonb_build_object('status', 'active', 'role', v_role::text),
    pg_catalog.jsonb_build_object('status', 'revoked'),
    pg_catalog.jsonb_build_object('profile_id', v_row.profile_id));

  return v_prior;
end;
$$;

-- ---------------------------------------------------------------------
-- Agent authority mutations. PRIME only. An agent can never be the
-- actor here, so no agent can raise its own authority.
-- ---------------------------------------------------------------------
create or replace function public.set_agent_authority(
  p_actor uuid,
  p_agent uuid,
  p_expected_level public.authority_level,
  p_level public.authority_level,
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.agents%rowtype;
  v_prior uuid;
begin
  select * into v_row from public.agents where id = p_agent for update;
  if not found then
    raise exception 'agent_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  v_prior := public.prior_request_audit(p_agent, 'agent.authority_changed', p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  if v_row.authority_level is distinct from p_expected_level then
    raise exception 'stale_status';
  end if;

  update public.agents set authority_level = p_level where id = p_agent;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    'agent.authority_changed', 'agent', p_agent, p_request_id, p_origin,
    pg_catalog.jsonb_build_object('authority_level', v_row.authority_level::text),
    pg_catalog.jsonb_build_object('authority_level', p_level::text),
    pg_catalog.jsonb_build_object('agent_code', v_row.code));

  return v_prior;
end;
$$;

create or replace function public.set_agent_active(
  p_actor uuid,
  p_agent uuid,
  p_expected_active boolean,
  p_active boolean,
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.agents%rowtype;
  v_action text;
  v_prior uuid;
begin
  select * into v_row from public.agents where id = p_agent for update;
  if not found then
    raise exception 'agent_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  v_action := case when p_active then 'agent.activated' else 'agent.deactivated' end;

  v_prior := public.prior_request_audit(p_agent, v_action, p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  if v_row.active is distinct from p_expected_active then
    raise exception 'stale_status';
  end if;

  update public.agents
  set active = p_active,
      status = case when p_active then 'active' else 'inactive' end
  where id = p_agent;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    v_action, 'agent', p_agent, p_request_id, p_origin,
    pg_catalog.jsonb_build_object('active', v_row.active),
    pg_catalog.jsonb_build_object('active', p_active),
    pg_catalog.jsonb_build_object('agent_code', v_row.code));

  return v_prior;
end;
$$;

create or replace function public.set_agent_financial_authority(
  p_actor uuid,
  p_agent uuid,
  p_expected_amount numeric,
  p_amount numeric,
  p_currency text,
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.agents%rowtype;
  v_prior uuid;
begin
  if p_amount < 0 then
    raise exception 'invalid_amount';
  end if;

  select * into v_row from public.agents where id = p_agent for update;
  if not found then
    raise exception 'agent_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  v_prior := public.prior_request_audit(p_agent, 'agent.financial_authority_changed', p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  if v_row.max_financial_authority is distinct from p_expected_amount then
    raise exception 'stale_status';
  end if;

  update public.agents
  set max_financial_authority = p_amount,
      currency = coalesce(p_currency, currency)
  where id = p_agent;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    'agent.financial_authority_changed', 'agent', p_agent, p_request_id, p_origin,
    pg_catalog.jsonb_build_object(
      'max_financial_authority', v_row.max_financial_authority, 'currency', v_row.currency),
    pg_catalog.jsonb_build_object(
      'max_financial_authority', p_amount,
      'currency', coalesce(p_currency, v_row.currency)),
    pg_catalog.jsonb_build_object('agent_code', v_row.code));

  return v_prior;
end;
$$;

create or replace function public.set_agent_action_types(
  p_actor uuid,
  p_agent uuid,
  p_allowed text[],
  p_prohibited text[],
  p_request_id text,
  p_origin text default 'web'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.agents%rowtype;
  v_prior uuid;
begin
  select * into v_row from public.agents where id = p_agent for update;
  if not found then
    raise exception 'agent_not_found';
  end if;

  perform public.assert_org_prime(p_actor, v_row.organization_id);

  v_prior := public.prior_request_audit(p_agent, 'agent.actions_changed', p_request_id);
  if v_prior is not null then
    return v_prior;
  end if;

  update public.agents
  set allowed_action_types = coalesce(p_allowed, allowed_action_types),
      prohibited_action_types = coalesce(p_prohibited, prohibited_action_types)
  where id = p_agent;

  v_prior := public.write_critical_audit(
    v_row.organization_id, v_row.business_id, 'user', p_actor,
    'agent.actions_changed', 'agent', p_agent, p_request_id, p_origin,
    pg_catalog.jsonb_build_object(
      'allowed', pg_catalog.to_jsonb(v_row.allowed_action_types),
      'prohibited', pg_catalog.to_jsonb(v_row.prohibited_action_types)),
    pg_catalog.jsonb_build_object(
      'allowed', pg_catalog.to_jsonb(coalesce(p_allowed, v_row.allowed_action_types)),
      'prohibited', pg_catalog.to_jsonb(
        coalesce(p_prohibited, v_row.prohibited_action_types))),
    pg_catalog.jsonb_build_object('agent_code', v_row.code));

  return v_prior;
end;
$$;

-- ---------------------------------------------------------------------
-- Grants: every RPC is service_role only. Browsers cannot call them.
-- ---------------------------------------------------------------------
-- Written out statement by statement rather than looped: an auditor must
-- be able to read the exact privilege granted on each function without
-- expanding a string.
revoke all on function public.create_approval_audited(
  uuid, uuid, uuid, uuid, text, jsonb, text, numeric, text,
  public.risk_level, timestamptz, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.create_approval_audited(
  uuid, uuid, uuid, uuid, text, jsonb, text, numeric, text,
  public.risk_level, timestamptz, text, text, jsonb) to service_role;

revoke all on function public.resolve_approval(
  uuid, uuid, public.approval_status, public.approval_status, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.resolve_approval(
  uuid, uuid, public.approval_status, public.approval_status, text, text, jsonb)
  to service_role;

revoke all on function public.expire_approvals(text, text) from public, anon, authenticated;
grant execute on function public.expire_approvals(text, text) to service_role;

revoke all on function public.record_approval_execution(
  uuid, public.approval_status, public.approval_status, jsonb, text, text)
  from public, anon, authenticated;
grant execute on function public.record_approval_execution(
  uuid, public.approval_status, public.approval_status, jsonb, text, text)
  to service_role;

revoke all on function public.assign_membership(
  uuid, uuid, uuid, uuid, public.role_key, public.authority_level, text, text)
  from public, anon, authenticated;
grant execute on function public.assign_membership(
  uuid, uuid, uuid, uuid, public.role_key, public.authority_level, text, text)
  to service_role;

revoke all on function public.change_membership_role(
  uuid, uuid, public.role_key, public.role_key, public.authority_level, text, text)
  from public, anon, authenticated;
grant execute on function public.change_membership_role(
  uuid, uuid, public.role_key, public.role_key, public.authority_level, text, text)
  to service_role;

revoke all on function public.revoke_membership(uuid, uuid, text, text)
  from public, anon, authenticated;
grant execute on function public.revoke_membership(uuid, uuid, text, text) to service_role;

revoke all on function public.set_agent_authority(
  uuid, uuid, public.authority_level, public.authority_level, text, text)
  from public, anon, authenticated;
grant execute on function public.set_agent_authority(
  uuid, uuid, public.authority_level, public.authority_level, text, text) to service_role;

revoke all on function public.set_agent_active(uuid, uuid, boolean, boolean, text, text)
  from public, anon, authenticated;
grant execute on function public.set_agent_active(uuid, uuid, boolean, boolean, text, text)
  to service_role;

revoke all on function public.set_agent_financial_authority(
  uuid, uuid, numeric, numeric, text, text, text) from public, anon, authenticated;
grant execute on function public.set_agent_financial_authority(
  uuid, uuid, numeric, numeric, text, text, text) to service_role;

revoke all on function public.set_agent_action_types(
  uuid, uuid, text[], text[], text, text) from public, anon, authenticated;
grant execute on function public.set_agent_action_types(
  uuid, uuid, text[], text[], text, text) to service_role;

-- Internal helpers are never granted to anyone: they are reachable only
-- from inside the definer functions above.
revoke all on function public.approval_transition_allowed(
  public.approval_status, public.approval_status, text) from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- Close the direct write paths. The RPCs above are now the only way to
-- mutate these tables from the application; without this the atomic
-- guarantee would be advisory rather than structural.
-- ---------------------------------------------------------------------
drop policy if exists approvals_update_prime on public.approvals;
drop policy if exists approvals_insert on public.approvals;
drop policy if exists memberships_write_prime on public.memberships;
drop policy if exists agents_write on public.agents;

-- Read access is preserved (memberships_select_prime and agents_select
-- already exist; approvals_select is unchanged).
