import 'server-only'
import { existsSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  buildGraph,
  buildReport,
  createFileStateStore,
  loadState,
  type GraphHealth,
  type GraphReport,
} from '@jarvis/graphify'
import { assessHealth } from '@jarvis/graphify'
import { createVault, createVaultFs, type Note, type SearchHit } from '@jarvis/obsidian'

// ---------------------------------------------------------------------
// Knowledge-layer integration.
//
// Both stores live on disk, and a deployed serverless function may not
// have either — the Graphify index is derived data that is deliberately
// not committed, and the vault is only present if file tracing carried
// it. So every reader here DEGRADES rather than throws.
//
// That choice is deliberate and worth stating: the knowledge layer is
// supporting context, not the product. A missing code index must never
// take down the page a customer-facing workflow lives on. Every function
// returns null or an empty list and the page says plainly that the store
// is unavailable, rather than rendering an error.
// ---------------------------------------------------------------------

/**
 * Resolves a store's location.
 *
 * An explicitly configured path is AUTHORITATIVE: if it is set and does
 * not exist, the answer is "unavailable", never a fallback. Falling
 * through would mean an operator who mistyped `JARVIS_VAULT_PATH`
 * silently reads a *different* vault than the one they configured, and
 * sees plausible content instead of an error — which is far worse than
 * an empty panel.
 *
 * Discovery only applies when nothing was configured. `process.cwd()`
 * differs between `next dev` (the app directory) and a built server, so
 * a single hard-coded relative path finds nothing in one of them.
 */
function resolveStorePath(configured: string | undefined, fallbacks: string[]): string | null {
  if (typeof configured === 'string' && configured !== '') {
    return existsSync(configured) ? configured : null
  }
  return fallbacks.find((candidate) => existsSync(candidate)) ?? null
}

function vaultPath(): string | null {
  return resolveStorePath(process.env.JARVIS_VAULT_PATH, [
    resolve(process.cwd(), 'farrokhirad-vault'),
    resolve(process.cwd(), '../../farrokhirad-vault'),
  ])
}

function graphIndexPath(): string | null {
  return resolveStorePath(process.env.JARVIS_GRAPH_INDEX, [
    resolve(process.cwd(), '.graphify-index.json'),
    resolve(process.cwd(), '../../.graphify-index.json'),
  ])
}

export interface VaultSnapshot {
  available: boolean
  notes: Note[]
  /** Populated only when a query was supplied. */
  hits: SearchHit[]
  countsByType: Record<string, number>
}

/**
 * Reads the vault, optionally filtered by a search query.
 *
 * Returns `available: false` rather than throwing when the vault is not
 * on disk, so the page can explain the absence instead of failing.
 */
export async function readVault(query?: string): Promise<VaultSnapshot> {
  const path = vaultPath()
  const empty: VaultSnapshot = { available: false, notes: [], hits: [], countsByType: {} }
  if (!path) return empty

  try {
    const vault = createVault(createVaultFs(path))
    const notes = await vault.notes()
    const trimmed = query?.trim() ?? ''
    const hits = trimmed.length >= 2 ? await vault.search(trimmed) : []

    const countsByType: Record<string, number> = {}
    for (const note of notes) {
      countsByType[note.frontmatter.type] = (countsByType[note.frontmatter.type] ?? 0) + 1
    }

    return { available: true, notes, hits, countsByType }
  } catch {
    return empty
  }
}

export interface GraphSnapshot {
  available: boolean
  report: GraphReport | null
  health: GraphHealth | null
}

/**
 * Reads the Graphify index.
 *
 * The index is regenerated by CI on every push and is not committed, so
 * `available: false` in a deployment is expected rather than a fault.
 */
export async function readGraph(): Promise<GraphSnapshot> {
  const path = graphIndexPath()
  const empty: GraphSnapshot = { available: false, report: null, health: null }
  if (!path) return empty

  try {
    const loaded = await loadState(createFileStateStore(path))
    if (Object.keys(loaded.state.files).length === 0) return empty

    const report = buildReport(buildGraph(loaded.state))
    return { available: true, report, health: assessHealth(loaded.state, report) }
  } catch {
    return empty
  }
}
